#!/usr/bin/python
# -*- coding: Windows-1252 -*-

NaturalEarthToGeoIP = {
'AFG': 'AF',
'AGO': 'AO',
'ALB': 'AL',
'ARE': 'AE',
'ARG': 'AR',
'ARM': 'AM',
'ATA': 'AQ',
'ATF': 'TF',
'AUS': 'AU',
'AUT': 'AT',
'AZE': 'AZ',
'BDI': 'BI',
'BEL': 'BE',
'BEN': 'BJ',
'BFA': 'BF',
'BGD': 'BD',
'BGR': 'BG',
'BHS': 'BS',
'BIH': 'BA',
'BLR': 'BY',
'BLZ': 'BZ',
'BOL': 'BO',
'BRA': 'BR',
'BRN': 'BN',
'BTN': 'BT',
'BWA': 'BW',
'CAF': 'CF',
'CAN': 'CA',
'CHE': 'CH',
'CHL': 'CL',
'CHN': 'CN',
'CIV': 'CI',
'CMR': 'CM',
'COD': 'CD',
'COG': 'CG',
'COL': 'CO',
'CRI': 'CR',
'CUB': 'CU',
'CYN': '',
'CYP': 'CY',
'CZE': 'CZ',
'DEU': 'DE',
'DJI': 'DJ',
'DNK': 'DK',
'DOM': 'DO',
'DZA': 'DZ',
'ECU': 'EC',
'EGY': 'EG',
'ENG': 'GB',
'ERI': 'ER',
'ESP': 'ES',
'EST': 'EE',
'ETH': 'ET',
'FIN': 'FI',
'FJI': 'FJ',
'FLK': 'FK',
'FXX': 'FR',
'GAB': 'GA',
'GEO': 'GE',
'GHA': 'GH',
'GIN': 'GN',
'GMB': 'GM',
'GNB': 'GW',
'GNQ': 'GQ',
'GRC': 'GR',
'GRL': 'GL',
'GTM': 'GT',
'GUF': 'GF',
'GUY': 'GY',
'HND': 'HN',
'HRV': 'HR',
'HTI': 'HT',
'HUN': 'HU',
'IDN': 'ID',
'IND': 'IN',
'IRL': 'IE',
'IRN': 'IR',
'IRQ': 'IQ',
'ISL': 'IS',
'ISR': 'IL',
'ITA': 'IT',
'JAM': 'JM',
'JOR': 'JO',
'JPN': 'JP',
'KAZ': 'KZ',
'KEN': 'KE',
'KGZ': 'KG',
'KHM': 'KH',
'KOR': 'KR',
'KOS': 'XK',
'KWT': 'KW',
'LAO': 'LA',
'LBN': 'LB',
'LBR': 'LR',
'LBY': 'LY',
'LKA': 'LK',
'LSO': 'LS',
'LTU': 'LT',
'LUX': 'LU',
'LVA': 'LV',
'MAR': 'MA',
'MDA': 'MD',
'MDG': 'MG',
'MEX': 'MX',
'MKD': 'MK',
'MLI': 'ML',
'MMR': 'MM',
'MNE': 'ME',
'MNG': 'MN',
'MOZ': 'MZ',
'MRT': 'MR',
'MWI': 'MW',
'MYS': 'MY',
'NAM': 'NA',
'NCL': 'NC',
'NER': 'NE',
'NGA': 'NG',
'NIC': 'NI',
'NIR': 'GB',
'NLD': 'NL',
'NOR': 'NO',
'NPL': 'NP',
'NSV': 'SJ',
'NZL': 'NZ',
'OMN': 'OM',
'PAK': 'PK',
'PAN': 'PA',
'PER': 'PE',
'PHL': 'PH',
'PNB': '',
'PNX': 'PG',
'POL': 'PL',
'PRI': 'PR',
'PRK': 'KP',
'PRT': 'PT',
'PRY': 'PY',
'QAT': 'QA',
'ROU': 'RO',
'RUS': 'RU',
'RWA': 'RW',
'SAH': 'EH',
'SAU': 'SA',
'SCT': '',
'SDN': 'SD',
'SDS': 'SS',
'SEN': 'SN',
'SLB': 'SB',
'SLE': 'SL',
'SLV': 'SV',
'SOL': '',
'SOM': 'SO',
'SRS': 'RS',
'SUR': 'SR',
'SVK': 'SK',
'SVN': 'SI',
'SWE': 'SE',
'SWZ': 'SZ',
'SYR': 'SY',
'TCD': 'TD',
'TGO': 'TG',
'THA': 'TH',
'TJK': 'TJ',
'TKM': 'TM',
'TLS': 'TL',
'TTO': 'TT',
'TUN': 'TN',
'TUR': 'TR',
'TWN': 'TW',
'TZA': 'TZ',
'UGA': 'UG',
'UKR': 'UA',
'URY': 'UY',
'USA': 'US',
'UZB': 'UZ',
'VEN': 'VE',
'VNM': 'VN',
'VUT': 'VU',
'WEB': 'PS',
'WLS': '',
'YEM': 'YE',
'ZAF': 'ZA',
'ZMB': 'ZM',
'ZWE': 'ZW',
}


GeoIPToNaturalEarth = {
'AF': 'AFG',
'AO': 'AGO',
'AL': 'ALB',
'AE': 'ARE',
'AR': 'ARG',
'AM': 'ARM',
'AQ': 'ATA',
'TF': 'ATF',
'AU': 'AUS',
'AT': 'AUT',
'AZ': 'AZE',
'BI': 'BDI',
'BE': 'BEL',
'BJ': 'BEN',
'BF': 'BFA',
'BD': 'BGD',
'BG': 'BGR',
'BS': 'BHS',
'BA': 'BIH',
'BY': 'BLR',
'BZ': 'BLZ',
'BO': 'BOL',
'BR': 'BRA',
'BN': 'BRN',
'BT': 'BTN',
'BW': 'BWA',
'CF': 'CAF',
'CA': 'CAN',
'CH': 'CHE',
'CL': 'CHL',
'CN': 'CHN',
'CI': 'CIV',
'CM': 'CMR',
'CD': 'COD',
'CG': 'COG',
'CO': 'COL',
'CR': 'CRI',
'CU': 'CUB',
'': 'CYN',
'CY': 'CYP',
'CZ': 'CZE',
'DE': 'DEU',
'DJ': 'DJI',
'DK': 'DNK',
'DO': 'DOM',
'DZ': 'DZA',
'EC': 'ECU',
'EG': 'EGY',
'GB': 'ENG',
'ER': 'ERI',
'ES': 'ESP',
'EE': 'EST',
'ET': 'ETH',
'FI': 'FIN',
'FJ': 'FJI',
'FK': 'FLK',
'FR': 'FXX',
'GA': 'GAB',
'GE': 'GEO',
'GH': 'GHA',
'GN': 'GIN',
'GM': 'GMB',
'GW': 'GNB',
'GQ': 'GNQ',
'GR': 'GRC',
'GL': 'GRL',
'GT': 'GTM',
'GF': 'GUF',
'GY': 'GUY',
'HN': 'HND',
'HR': 'HRV',
'HT': 'HTI',
'HU': 'HUN',
'ID': 'IDN',
'IN': 'IND',
'IE': 'IRL',
'IR': 'IRN',
'IQ': 'IRQ',
'IS': 'ISL',
'IL': 'ISR',
'IT': 'ITA',
'JM': 'JAM',
'JO': 'JOR',
'JP': 'JPN',
'KZ': 'KAZ',
'KE': 'KEN',
'KG': 'KGZ',
'KH': 'KHM',
'KR': 'KOR',
'XK': 'KOS',
'KW': 'KWT',
'LA': 'LAO',
'LB': 'LBN',
'LR': 'LBR',
'LY': 'LBY',
'LK': 'LKA',
'LS': 'LSO',
'LT': 'LTU',
'LU': 'LUX',
'LV': 'LVA',
'MA': 'MAR',
'MD': 'MDA',
'MG': 'MDG',
'MX': 'MEX',
'MK': 'MKD',
'ML': 'MLI',
'MM': 'MMR',
'ME': 'MNE',
'MN': 'MNG',
'MZ': 'MOZ',
'MR': 'MRT',
'MW': 'MWI',
'MY': 'MYS',
'NA': 'NAM',
'NC': 'NCL',
'NE': 'NER',
'NG': 'NGA',
'NI': 'NIC',
'GB': 'NIR',
'NL': 'NLD',
'NO': 'NOR',
'NP': 'NPL',
'SJ': 'NSV',
'NZ': 'NZL',
'OM': 'OMN',
'PK': 'PAK',
'PA': 'PAN',
'PE': 'PER',
'PH': 'PHL',
'': 'PNB',
'PG': 'PNX',
'PL': 'POL',
'PR': 'PRI',
'KP': 'PRK',
'PT': 'PRT',
'PY': 'PRY',
'QA': 'QAT',
'RO': 'ROU',
'RU': 'RUS',
'RW': 'RWA',
'EH': 'SAH',
'SA': 'SAU',
'': 'SCT',
'SD': 'SDN',
'SS': 'SDS',
'SN': 'SEN',
'SB': 'SLB',
'SL': 'SLE',
'SV': 'SLV',
'': 'SOL',
'SO': 'SOM',
'RS': 'SRS',
'SR': 'SUR',
'SK': 'SVK',
'SI': 'SVN',
'SE': 'SWE',
'SZ': 'SWZ',
'SY': 'SYR',
'TD': 'TCD',
'TG': 'TGO',
'TH': 'THA',
'TJ': 'TJK',
'TM': 'TKM',
'TL': 'TLS',
'TT': 'TTO',
'TN': 'TUN',
'TR': 'TUR',
'TW': 'TWN',
'TZ': 'TZA',
'UG': 'UGA',
'UA': 'UKR',
'UY': 'URY',
'US': 'USA',
'UZ': 'UZB',
'VE': 'VEN',
'VN': 'VNM',
'VU': 'VUT',
'PS': 'WEB',
'': 'WLS',
'YE': 'YEM',
'ZA': 'ZAF',
'ZM': 'ZMB',
'ZW': 'ZWE',
}


NaturalEarthToName = {
"AFG": "Afghanistan",
"AGO": "Angola",
"ALB": "Albania",
"ARE": "United Arab Emirates",
"ARG": "Argentina",
"ARM": "Armenia",
"ATA": "Antarctica",
"ATF": "Fr. S. Antarctic Lands",
"AUS": "Australia",
"AUT": "Austria",
"AZE": "Azerbaijan",
"BDI": "Burundi",
"BEL": "Belgium",
"BEN": "Benin",
"BFA": "Burkina Faso",
"BGD": "Bangladesh",
"BGR": "Bulgaria",
"BHS": "Bahamas",
"BIH": "Bosnia and Herz.",
"BLR": "Belarus",
"BLZ": "Belize",
"BOL": "Bolivia",
"BRA": "Brazil",
"BRN": "Brunei",
"BTN": "Bhutan",
"BWA": "Botswana",
"CAF": "Central African Rep.",
"CAN": "Canada",
"CHE": "Switzerland",
"CHL": "Chile",
"CHN": "China",
"CIV": "Côte d'Ivoire",
"CMR": "Cameroon",
"COD": "Dem. Rep. Congo",
"COG": "Congo",
"COL": "Colombia",
"CRI": "Costa Rica",
"CUB": "Cuba",
"CYN": "N. Cyprus",
"CYP": "Cyprus",
"CZE": "Czech Rep.",
"DEU": "Germany",
"DJI": "Djibouti",
"DNK": "Denmark",
"DOM": "Dominican Rep.",
"DZA": "Algeria",
"ECU": "Ecuador",
"EGY": "Egypt",
"ENG": "England",
"ERI": "Eritrea",
"ESP": "Spain",
"EST": "Estonia",
"ETH": "Ethiopia",
"FIN": "Finland",
"FJI": "Fiji",
"FLK": "Falkland Is.",
"FXX": "France",
"GAB": "Gabon",
"GEO": "Georgia",
"GHA": "Ghana",
"GIN": "Guinea",
"GMB": "Gambia",
"GNB": "Guinea-Bissau",
"GNQ": "Eq. Guinea",
"GRC": "Greece",
"GRL": "Greenland",
"GTM": "Guatemala",
"GUF": "French Guiana",
"GUY": "Guyana",
"HND": "Honduras",
"HRV": "Croatia",
"HTI": "Haiti",
"HUN": "Hungary",
"IDN": "Indonesia",
"IND": "India",
"IRL": "Ireland",
"IRN": "Iran",
"IRQ": "Iraq",
"ISL": "Iceland",
"ISR": "Israel",
"ITA": "Italy",
"JAM": "Jamaica",
"JOR": "Jordan",
"JPN": "Japan",
"KAZ": "Kazakhstan",
"KEN": "Kenya",
"KGZ": "Kyrgyzstan",
"KHM": "Cambodia",
"KOR": "Korea",
"KOS": "Kosovo",
"KWT": "Kuwait",
"LAO": "Lao PDR",
"LBN": "Lebanon",
"LBR": "Liberia",
"LBY": "Libya",
"LKA": "Sri Lanka",
"LSO": "Lesotho",
"LTU": "Lithuania",
"LUX": "Luxembourg",
"LVA": "Latvia",
"MAR": "Morocco",
"MDA": "Moldova",
"MDG": "Madagascar",
"MEX": "Mexico",
"MKD": "Macedonia",
"MLI": "Mali",
"MMR": "Myanmar",
"MNE": "Montenegro",
"MNG": "Mongolia",
"MOZ": "Mozambique",
"MRT": "Mauritania",
"MWI": "Malawi",
"MYS": "Malaysia",
"NAM": "Namibia",
"NCL": "New Caledonia",
"NER": "Niger",
"NGA": "Nigeria",
"NIC": "Nicaragua",
"NIR": "N. Ireland",
"NLD": "Netherlands",
"NOR": "Norway",
"NPL": "Nepal",
"NSV": "Svalbard Is.",
"NZL": "New Zealand",
"OMN": "Oman",
"PAK": "Pakistan",
"PAN": "Panama",
"PER": "Peru",
"PHL": "Philippines",
"PNB": "Bougainville",
"PNX": "Papua New Guinea",
"POL": "Poland",
"PRI": "Puerto Rico",
"PRK": "Dem. Rep. Korea",
"PRT": "Portugal",
"PRY": "Paraguay",
"QAT": "Qatar",
"ROU": "Romania",
"RUS": "Russia",
"RWA": "Rwanda",
"SAH": "W. Sahara",
"SAU": "Saudi Arabia",
"SCT": "Scotland",
"SDN": "Sudan",
"SDS": "S. Sudan",
"SEN": "Senegal",
"SLB": "Solomon Is.",
"SLE": "Sierra Leone",
"SLV": "El Salvador",
"SOL": "Somaliland",
"SOM": "Somalia",
"SRS": "Serbia",
"SUR": "Suriname",
"SVK": "Slovakia",
"SVN": "Slovenia",
"SWE": "Sweden",
"SWZ": "Swaziland",
"SYR": "Syria",
"TCD": "Chad",
"TGO": "Togo",
"THA": "Thailand",
"TJK": "Tajikistan",
"TKM": "Turkmenistan",
"TLS": "Timor-Leste",
"TTO": "Trinidad and Tobago",
"TUN": "Tunisia",
"TUR": "Turkey",
"TWN": "Taiwan",
"TZA": "Tanzania",
"UGA": "Uganda",
"UKR": "Ukraine",
"URY": "Uruguay",
"USA": "United States",
"UZB": "Uzbekistan",
"VEN": "Venezuela",
"VNM": "Vietnam",
"VUT": "Vanuatu",
"WEB": "West Bank",
"WLS": "Wales",
"YEM": "Yemen",
"ZAF": "South Africa",
"ZMB": "Zambia",
"ZWE": "Zimbabwe",
}


NameToNaturalEarth = {
"Afghanistan": "AFG",
"Angola": "AGO",
"Albania": "ALB",
"United Arab Emirates": "ARE",
"Argentina": "ARG",
"Armenia": "ARM",
"Antarctica": "ATA",
"Fr. S. Antarctic Lands": "ATF",
"Australia": "AUS",
"Austria": "AUT",
"Azerbaijan": "AZE",
"Burundi": "BDI",
"Belgium": "BEL",
"Benin": "BEN",
"Burkina Faso": "BFA",
"Bangladesh": "BGD",
"Bulgaria": "BGR",
"Bahamas": "BHS",
"Bosnia and Herz.": "BIH",
"Belarus": "BLR",
"Belize": "BLZ",
"Bolivia": "BOL",
"Brazil": "BRA",
"Brunei": "BRN",
"Bhutan": "BTN",
"Botswana": "BWA",
"Central African Rep.": "CAF",
"Canada": "CAN",
"Switzerland": "CHE",
"Chile": "CHL",
"China": "CHN",
"Côte d'Ivoire": "CIV",
"Cameroon": "CMR",
"Dem. Rep. Congo": "COD",
"Congo": "COG",
"Colombia": "COL",
"Costa Rica": "CRI",
"Cuba": "CUB",
"N. Cyprus": "CYN",
"Cyprus": "CYP",
"Czech Rep.": "CZE",
"Germany": "DEU",
"Djibouti": "DJI",
"Denmark": "DNK",
"Dominican Rep.": "DOM",
"Algeria": "DZA",
"Ecuador": "ECU",
"Egypt": "EGY",
"England": "ENG",
"Eritrea": "ERI",
"Spain": "ESP",
"Estonia": "EST",
"Ethiopia": "ETH",
"Finland": "FIN",
"Fiji": "FJI",
"Falkland Is.": "FLK",
"France": "FXX",
"Gabon": "GAB",
"Georgia": "GEO",
"Ghana": "GHA",
"Guinea": "GIN",
"Gambia": "GMB",
"Guinea-Bissau": "GNB",
"Eq. Guinea": "GNQ",
"Greece": "GRC",
"Greenland": "GRL",
"Guatemala": "GTM",
"French Guiana": "GUF",
"Guyana": "GUY",
"Honduras": "HND",
"Croatia": "HRV",
"Haiti": "HTI",
"Hungary": "HUN",
"Indonesia": "IDN",
"India": "IND",
"Ireland": "IRL",
"Iran": "IRN",
"Iraq": "IRQ",
"Iceland": "ISL",
"Israel": "ISR",
"Italy": "ITA",
"Jamaica": "JAM",
"Jordan": "JOR",
"Japan": "JPN",
"Kazakhstan": "KAZ",
"Kenya": "KEN",
"Kyrgyzstan": "KGZ",
"Cambodia": "KHM",
"Korea": "KOR",
"Kosovo": "KOS",
"Kuwait": "KWT",
"Lao PDR": "LAO",
"Lebanon": "LBN",
"Liberia": "LBR",
"Libya": "LBY",
"Sri Lanka": "LKA",
"Lesotho": "LSO",
"Lithuania": "LTU",
"Luxembourg": "LUX",
"Latvia": "LVA",
"Morocco": "MAR",
"Moldova": "MDA",
"Madagascar": "MDG",
"Mexico": "MEX",
"Macedonia": "MKD",
"Mali": "MLI",
"Myanmar": "MMR",
"Montenegro": "MNE",
"Mongolia": "MNG",
"Mozambique": "MOZ",
"Mauritania": "MRT",
"Malawi": "MWI",
"Malaysia": "MYS",
"Namibia": "NAM",
"New Caledonia": "NCL",
"Niger": "NER",
"Nigeria": "NGA",
"Nicaragua": "NIC",
"N. Ireland": "NIR",
"Netherlands": "NLD",
"Norway": "NOR",
"Nepal": "NPL",
"Svalbard Is.": "NSV",
"New Zealand": "NZL",
"Oman": "OMN",
"Pakistan": "PAK",
"Panama": "PAN",
"Peru": "PER",
"Philippines": "PHL",
"Bougainville": "PNB",
"Papua New Guinea": "PNX",
"Poland": "POL",
"Puerto Rico": "PRI",
"Dem. Rep. Korea": "PRK",
"Portugal": "PRT",
"Paraguay": "PRY",
"Qatar": "QAT",
"Romania": "ROU",
"Russia": "RUS",
"Rwanda": "RWA",
"W. Sahara": "SAH",
"Saudi Arabia": "SAU",
"Scotland": "SCT",
"Sudan": "SDN",
"S. Sudan": "SDS",
"Senegal": "SEN",
"Solomon Is.": "SLB",
"Sierra Leone": "SLE",
"El Salvador": "SLV",
"Somaliland": "SOL",
"Somalia": "SOM",
"Serbia": "SRS",
"Suriname": "SUR",
"Slovakia": "SVK",
"Slovenia": "SVN",
"Sweden": "SWE",
"Swaziland": "SWZ",
"Syria": "SYR",
"Chad": "TCD",
"Togo": "TGO",
"Thailand": "THA",
"Tajikistan": "TJK",
"Turkmenistan": "TKM",
"Timor-Leste": "TLS",
"Trinidad and Tobago": "TTO",
"Tunisia": "TUN",
"Turkey": "TUR",
"Taiwan": "TWN",
"Tanzania": "TZA",
"Uganda": "UGA",
"Ukraine": "UKR",
"Uruguay": "URY",
"United States": "USA",
"Uzbekistan": "UZB",
"Venezuela": "VEN",
"Vietnam": "VNM",
"Vanuatu": "VUT",
"West Bank": "WEB",
"Wales": "WLS",
"Yemen": "YEM",
"South Africa": "ZAF",
"Zambia": "ZMB",
"Zimbabwe": "ZWE",
}


GeoIPToName = {
"AF": "Afghanistan",
"AO": "Angola",
"AL": "Albania",
"AE": "United Arab Emirates",
"AR": "Argentina",
"AM": "Armenia",
"AQ": "Antarctica",
"TF": "Fr. S. Antarctic Lands",
"AU": "Australia",
"AT": "Austria",
"AZ": "Azerbaijan",
"BI": "Burundi",
"BE": "Belgium",
"BJ": "Benin",
"BF": "Burkina Faso",
"BD": "Bangladesh",
"BG": "Bulgaria",
"BS": "Bahamas",
"BA": "Bosnia and Herz.",
"BY": "Belarus",
"BZ": "Belize",
"BO": "Bolivia",
"BR": "Brazil",
"BN": "Brunei",
"BT": "Bhutan",
"BW": "Botswana",
"CF": "Central African Rep.",
"CA": "Canada",
"CH": "Switzerland",
"CL": "Chile",
"CN": "China",
"CI": "Côte d'Ivoire",
"CM": "Cameroon",
"CD": "Dem. Rep. Congo",
"CG": "Congo",
"CO": "Colombia",
"CR": "Costa Rica",
"CU": "Cuba",
"": "N. Cyprus",
"CY": "Cyprus",
"CZ": "Czech Rep.",
"DE": "Germany",
"DJ": "Djibouti",
"DK": "Denmark",
"DO": "Dominican Rep.",
"DZ": "Algeria",
"EC": "Ecuador",
"EG": "Egypt",
"GB": "England",
"ER": "Eritrea",
"ES": "Spain",
"EE": "Estonia",
"ET": "Ethiopia",
"FI": "Finland",
"FJ": "Fiji",
"FK": "Falkland Is.",
"FR": "France",
"GA": "Gabon",
"GE": "Georgia",
"GH": "Ghana",
"GN": "Guinea",
"GM": "Gambia",
"GW": "Guinea-Bissau",
"GQ": "Eq. Guinea",
"GR": "Greece",
"GL": "Greenland",
"GT": "Guatemala",
"GF": "French Guiana",
"GY": "Guyana",
"HN": "Honduras",
"HR": "Croatia",
"HT": "Haiti",
"HU": "Hungary",
"ID": "Indonesia",
"IN": "India",
"IE": "Ireland",
"IR": "Iran",
"IQ": "Iraq",
"IS": "Iceland",
"IL": "Israel",
"IT": "Italy",
"JM": "Jamaica",
"JO": "Jordan",
"JP": "Japan",
"KZ": "Kazakhstan",
"KE": "Kenya",
"KG": "Kyrgyzstan",
"KH": "Cambodia",
"KR": "Korea",
"XK": "Kosovo",
"KW": "Kuwait",
"LA": "Lao PDR",
"LB": "Lebanon",
"LR": "Liberia",
"LY": "Libya",
"LK": "Sri Lanka",
"LS": "Lesotho",
"LT": "Lithuania",
"LU": "Luxembourg",
"LV": "Latvia",
"MA": "Morocco",
"MD": "Moldova",
"MG": "Madagascar",
"MX": "Mexico",
"MK": "Macedonia",
"ML": "Mali",
"MM": "Myanmar",
"ME": "Montenegro",
"MN": "Mongolia",
"MZ": "Mozambique",
"MR": "Mauritania",
"MW": "Malawi",
"MY": "Malaysia",
"NA": "Namibia",
"NC": "New Caledonia",
"NE": "Niger",
"NG": "Nigeria",
"NI": "Nicaragua",
"GB": "N. Ireland",
"NL": "Netherlands",
"NO": "Norway",
"NP": "Nepal",
"SJ": "Svalbard Is.",
"NZ": "New Zealand",
"OM": "Oman",
"PK": "Pakistan",
"PA": "Panama",
"PE": "Peru",
"PH": "Philippines",
"": "Bougainville",
"PG": "Papua New Guinea",
"PL": "Poland",
"PR": "Puerto Rico",
"KP": "Dem. Rep. Korea",
"PT": "Portugal",
"PY": "Paraguay",
"QA": "Qatar",
"RO": "Romania",
"RU": "Russia",
"RW": "Rwanda",
"EH": "W. Sahara",
"SA": "Saudi Arabia",
"": "Scotland",
"SD": "Sudan",
"SS": "S. Sudan",
"SN": "Senegal",
"SB": "Solomon Is.",
"SL": "Sierra Leone",
"SV": "El Salvador",
"": "Somaliland",
"SO": "Somalia",
"RS": "Serbia",
"SR": "Suriname",
"SK": "Slovakia",
"SI": "Slovenia",
"SE": "Sweden",
"SZ": "Swaziland",
"SY": "Syria",
"TD": "Chad",
"TG": "Togo",
"TH": "Thailand",
"TJ": "Tajikistan",
"TM": "Turkmenistan",
"TL": "Timor-Leste",
"TT": "Trinidad and Tobago",
"TN": "Tunisia",
"TR": "Turkey",
"TW": "Taiwan",
"TZ": "Tanzania",
"UG": "Uganda",
"UA": "Ukraine",
"UY": "Uruguay",
"US": "United States",
"UZ": "Uzbekistan",
"VE": "Venezuela",
"VN": "Vietnam",
"VU": "Vanuatu",
"PS": "West Bank",
"": "Wales",
"YE": "Yemen",
"ZA": "South Africa",
"ZM": "Zambia",
"ZW": "Zimbabwe",
}


NameToGeoIP = {
"Afghanistan": "AF",
"Angola": "AO",
"Albania": "AL",
"United Arab Emirates": "AE",
"Argentina": "AR",
"Armenia": "AM",
"Antarctica": "AQ",
"Fr. S. Antarctic Lands": "TF",
"Australia": "AU",
"Austria": "AT",
"Azerbaijan": "AZ",
"Burundi": "BI",
"Belgium": "BE",
"Benin": "BJ",
"Burkina Faso": "BF",
"Bangladesh": "BD",
"Bulgaria": "BG",
"Bahamas": "BS",
"Bosnia and Herz.": "BA",
"Belarus": "BY",
"Belize": "BZ",
"Bolivia": "BO",
"Brazil": "BR",
"Brunei": "BN",
"Bhutan": "BT",
"Botswana": "BW",
"Central African Rep.": "CF",
"Canada": "CA",
"Switzerland": "CH",
"Chile": "CL",
"China": "CN",
"Côte d'Ivoire": "CI",
"Cameroon": "CM",
"Dem. Rep. Congo": "CD",
"Congo": "CG",
"Colombia": "CO",
"Costa Rica": "CR",
"Cuba": "CU",
"N. Cyprus": "",
"Cyprus": "CY",
"Czech Rep.": "CZ",
"Germany": "DE",
"Djibouti": "DJ",
"Denmark": "DK",
"Dominican Rep.": "DO",
"Algeria": "DZ",
"Ecuador": "EC",
"Egypt": "EG",
"England": "GB",
"Eritrea": "ER",
"Spain": "ES",
"Estonia": "EE",
"Ethiopia": "ET",
"Finland": "FI",
"Fiji": "FJ",
"Falkland Is.": "FK",
"France": "FR",
"Gabon": "GA",
"Georgia": "GE",
"Ghana": "GH",
"Guinea": "GN",
"Gambia": "GM",
"Guinea-Bissau": "GW",
"Eq. Guinea": "GQ",
"Greece": "GR",
"Greenland": "GL",
"Guatemala": "GT",
"French Guiana": "GF",
"Guyana": "GY",
"Honduras": "HN",
"Croatia": "HR",
"Haiti": "HT",
"Hungary": "HU",
"Indonesia": "ID",
"India": "IN",
"Ireland": "IE",
"Iran": "IR",
"Iraq": "IQ",
"Iceland": "IS",
"Israel": "IL",
"Italy": "IT",
"Jamaica": "JM",
"Jordan": "JO",
"Japan": "JP",
"Kazakhstan": "KZ",
"Kenya": "KE",
"Kyrgyzstan": "KG",
"Cambodia": "KH",
"Korea": "KR",
"Kosovo": "XK",
"Kuwait": "KW",
"Lao PDR": "LA",
"Lebanon": "LB",
"Liberia": "LR",
"Libya": "LY",
"Sri Lanka": "LK",
"Lesotho": "LS",
"Lithuania": "LT",
"Luxembourg": "LU",
"Latvia": "LV",
"Morocco": "MA",
"Moldova": "MD",
"Madagascar": "MG",
"Mexico": "MX",
"Macedonia": "MK",
"Mali": "ML",
"Myanmar": "MM",
"Montenegro": "ME",
"Mongolia": "MN",
"Mozambique": "MZ",
"Mauritania": "MR",
"Malawi": "MW",
"Malaysia": "MY",
"Namibia": "NA",
"New Caledonia": "NC",
"Niger": "NE",
"Nigeria": "NG",
"Nicaragua": "NI",
"N. Ireland": "GB",
"Netherlands": "NL",
"Norway": "NO",
"Nepal": "NP",
"Svalbard Is.": "SJ",
"New Zealand": "NZ",
"Oman": "OM",
"Pakistan": "PK",
"Panama": "PA",
"Peru": "PE",
"Philippines": "PH",
"Bougainville": "",
"Papua New Guinea": "PG",
"Poland": "PL",
"Puerto Rico": "PR",
"Dem. Rep. Korea": "KP",
"Portugal": "PT",
"Paraguay": "PY",
"Qatar": "QA",
"Romania": "RO",
"Russia": "RU",
"Rwanda": "RW",
"W. Sahara": "EH",
"Saudi Arabia": "SA",
"Scotland": "",
"Sudan": "SD",
"S. Sudan": "SS",
"Senegal": "SN",
"Solomon Is.": "SB",
"Sierra Leone": "SL",
"El Salvador": "SV",
"Somaliland": "",
"Somalia": "SO",
"Serbia": "RS",
"Suriname": "SR",
"Slovakia": "SK",
"Slovenia": "SI",
"Sweden": "SE",
"Swaziland": "SZ",
"Syria": "SY",
"Chad": "TD",
"Togo": "TG",
"Thailand": "TH",
"Tajikistan": "TJ",
"Turkmenistan": "TM",
"Timor-Leste": "TL",
"Trinidad and Tobago": "TT",
"Tunisia": "TN",
"Turkey": "TR",
"Taiwan": "TW",
"Tanzania": "TZ",
"Uganda": "UG",
"Ukraine": "UA",
"Uruguay": "UY",
"United States": "US",
"Uzbekistan": "UZ",
"Venezuela": "VE",
"Vietnam": "VN",
"Vanuatu": "VU",
"West Bank": "PS",
"Wales": "",
"Yemen": "YE",
"South Africa": "ZA",
"Zambia": "ZM",
"Zimbabwe": "ZW",
}
